name: Build and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # Verify that this is the original repository to prevent accidental runs in forks.
  check-repository:
    runs-on: ubuntu-latest
    outputs:
      is_correct_repo: ${{ steps.check.outputs.is_correct_repo }}
    steps:
      - name: Repository validation
        id: check
        run: |
          # This check prevents accidental runs in forked repositories
          # To disable for forks, comment/remove this entire job
          if [ "$GITHUB_REPOSITORY" = "scribe-org/Scribe-Data" ]; then
            echo "is_correct_repo=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_correct_repo=false" >> "$GITHUB_OUTPUT"
            echo "::warning::This workflow is restricted to scribe-org/Scribe-Data"
          fi

  docker:
    needs: check-repository
    if: needs.check-repository.outputs.is_correct_repo == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Docker Hub authentication
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: scribe-org/scribe-data:latest
