name: Python Package CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.9"

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create Environment and Install Dependencies
        run: |
          python -m pip install --upgrade uv
          uv venv
          if [ "$RUNNER_OS" == "Windows" ]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
          echo PATH=$PATH >> $GITHUB_ENV
          uv pip install -r backend/requirements-dev.txt

      - name: Set up Homebrew
        if: matrix.os == 'macos-latest'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install PyICU dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install icu4c
          # Configure PATH & PKG_CONFIG_PATH as in https://gitlab.pyicu.org/main/pyicu.
          export PATH="$(brew --prefix)/opt/icu4c/bin:$(brew --prefix)/opt/icu4c/sbin:$PATH"
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$(brew --prefix)/opt/icu4c/lib/pkgconfig"

      - name: Run Ruff Format - Formatting Check
        run: ruff format ./src

      - name: Run Ruff - Linting and Import Sorting Check
        if: always()
        run: ruff check ./src

      - name: Run mypy - Static Type Checking
        if: always()
        run: mypy ./src --config-file ./pyproject.toml

      - name: Run pytest - Unit Tests
        if: always()
        run: pytest . --cov=. --cov-report=term-missing --cov-fail-under=60 --cov-config=./pyproject.toml
